"""Core simulator: closed-loop (A) and step-matched open-loop (B) boundaries.

System A (closed loop)
    Observer A1 always reports an independent observation of reliability rho.
    Observer A2, at each t >= 2, repeats the decision agent's previous
    announcement a_{t-1} with probability kappa; otherwise it reports its own
    independent observation of reliability rho. A sensory state therefore has an
    active state among its causal ancestors.

System B (open loop)
    Observer A2 is an independent sensor whose reliability at step t equals the
    marginal reliability rho_eff[t] of s2_t in A. Per step, p_A(s_t | eta) and
    p_B(s_t | eta) coincide (Proposition 1).

Agents
    "naive"   factorised likelihood with the exact per-step marginal rho_eff[t].
    "aligned" models the path a_{t-1} -> s2_t with the true kappa (efference copy).
"""
from __future__ import annotations

import numpy as np

SEED = 20260930


def logit(p):
    """Log-odds of a probability (array-friendly)."""
    return np.log(p / (1 - p))


def decide(L: np.ndarray, rng: np.random.Generator) -> np.ndarray:
    """Greedy announcement from log-odds of eta = 1, ties broken uniformly."""
    a = (L > 0).astype(int)
    tie = L == 0
    a[tie] = rng.integers(0, 2, tie.sum())
    return a


def simulate(system: str, agent: str, N: int, T: int, rho: float, kappa: float,
             reff, seed: int = SEED, track: bool = False) -> dict:
    """Simulate N independent episodes of T steps.

    Parameters
    ----------
    system : "A" (closed loop) or "B" (open loop).
    agent  : "naive" or "aligned".
    reff   : array of length T, per-step marginal reliability of s2 (used by the
             naive agent and by system B).

    Returns a dict with per-step arrays ``acc`` (P(a_t = eta)), ``conf``
    (mean max posterior), ``s2acc`` (empirical P(s2_t = eta)), and ``final``
    summary statistics. With ``track=True`` also returns ``wrong`` (T x N).
    """
    if system not in ("A", "B"):
        raise ValueError("system must be 'A' or 'B'")
    if agent not in ("naive", "aligned"):
        raise ValueError("agent must be 'naive' or 'aligned'")
    reff = np.asarray(reff, dtype=float)
    rng = np.random.default_rng(seed)
    eta = rng.integers(0, 2, N)
    L = np.zeros(N)
    a_prev = None
    acc, conf, s2acc, wrong_hist = [], [], [], []
    for t in range(T):
        s1 = np.where(rng.random(N) < rho, eta, 1 - eta)
        ind2 = np.where(rng.random(N) < rho, eta, 1 - eta)
        u_copy = rng.random(N)
        u_B = rng.random(N)
        if system == "A":
            s2 = ind2 if t == 0 else np.where(u_copy < kappa, a_prev, ind2)
        else:
            s2 = np.where(u_B < reff[t], eta, 1 - eta)
        s2acc.append(np.mean(s2 == eta))

        L = L + (2 * s1 - 1) * logit(rho)
        if agent == "naive":
            L = L + (2 * s2 - 1) * logit(reff[t])
        else:
            if t == 0 or kappa == 0:
                L = L + (2 * s2 - 1) * logit(rho)
            else:
                same = (s2 == a_prev)
                p1 = kappa * same + (1 - kappa) * np.where(s2 == 1, rho, 1 - rho)
                p0 = kappa * same + (1 - kappa) * np.where(s2 == 0, rho, 1 - rho)
                L = L + np.log(p1) - np.log(p0)
        a = decide(L, rng)
        a_prev = a
        p = 1 / (1 + np.exp(-L))
        acc.append(np.mean(a == eta))
        conf.append(np.mean(np.maximum(p, 1 - p)))
        if track:
            wrong_hist.append(a != eta)
    p = 1 / (1 + np.exp(-L))
    p_true = np.where(eta == 1, p, 1 - p)
    final = dict(
        accuracy=float(np.mean(a_prev == eta)),
        mean_confidence=float(np.mean(np.maximum(p, 1 - p))),
        lockin=float(np.mean(p_true < 0.01)),
        log_loss=float(np.mean(-np.log(np.clip(p_true, 1e-300, 1)))),
    )
    out = dict(acc=np.array(acc), conf=np.array(conf), s2acc=np.array(s2acc), final=final)
    if track:
        out["wrong"] = np.array(wrong_hist)
    return out


def fixed_point_reff(N: int, T: int, rho: float, kappa: float, iters: int = 40,
                     tol: float = 1e-4, seed: int = SEED) -> np.ndarray:
    """Self-consistent per-step marginal reliability of s2 in system A when the
    announcements are generated by the naive agent (a Berk-Nash-style fixed point)."""
    reff = np.full(T, rho)
    for _ in range(iters):
        s2acc = simulate("A", "naive", N, T, rho, kappa, reff, seed=seed)["s2acc"]
        new = np.clip(s2acc, 0.5 + 1e-6, 1 - 1e-6)
        new[0] = rho
        done = np.max(np.abs(new - reff)) < tol
        reff = new
        if done:
            break
    return reff
